disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - private_outlet
  - vertical_whitespace

included:
  - src/barista

excluded:
  - Pods
  - Carthage
  - fastlane
  - vendor
  - DerivedData
  - build

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y

reporter: "xcode"
